### ISSUE TITLE
Emissive materials not working anymore

### ISSUE THREAD

**Issue by jtorresfabra** [cedricpinson/osgjs#255] opened 2015-02-18 13:27 UTC
It seems the emissive component is not used anymore. In fact the uniform MaterialEmission is declared in the shader but not used. I have some test data, just in case you need it. 
@Kuranes @cedricpinson could you take a look?

**Comment by Kuranes** [comment] 2015-02-18 14:37
https://github.com/cedricpinson/osgjs/blob/develop/sources/osgShader/Compiler.js#L696
 materialUniforms.emission => materialUniforms.materialemission

**Comment by jtorresfabra** [comment] 2015-02-18 14:50
Thanks for taking a look @Kuranes 

There is a Uniform declared (MaterialEmission) that is not used in the shader code at all. You can see it with webGL inspector or other extensions. I guess it should be removed then.

Also, are you able to change the apparience of any model using the emissive component in the materials example? I'm not. 

I'm preparing also some screenshots of what I saw time ago with my own models and what I see now.

**Comment by Kuranes** [comment] 2015-02-18 15:01
It was broken indeed, Pushed the fix and the sample material works now when I change materials.
Hopefully it fixes the bug on your side ?

**Comment by jtorresfabra** [comment] 2015-02-18 15:23
It fixes the materials example, now it works as expected. 

Thank you!!

**Comment by jtorresfabra** [comment] 2015-02-18 15:53
@Kuranes I think I've seen a different issue with the material emissive component. If a model does not have normals attached the emissive material should work, as it does not depend on lighting/normals.
Now it does not work.

**Comment by Kuranes** [comment] 2015-02-18 16:07
The model in the sample material have normals.
Maybe a specific configuration, could you provide a repro case I could check ?

**Comment by jtorresfabra** [comment] 2015-02-18 16:18
What i've done to test is to use the example quad-texture, after commenting
the assignment of normals in createTexturedQuad in Shape.js. It's enough to
reproduce it. Sorry for not sending the model but I'm out the office now
and writting from my phone.
Thanks.

El miércoles, 18 de febrero de 2015, Tuan Kuranes <notifications@github.com>
escribió:

> The model in the sample material have normals.
> Maybe a specific configuration, could you provide a repro case I could
> check ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cedricpinson/osgjs/issues/255#issuecomment-74890934>.
>


-- 
Jordi Torres

**Comment by Kuranes** [comment] 2015-02-18 16:54
Made an update on the PR, bugfix thanks to @stephomi ( the "no-light" case was broken ).
Tell me if that fixes it for you ?

**Comment by jtorresfabra** [comment] 2015-02-19 07:33
Ummm, it's amost fixed, I think the emission color should be merged with the texture color if there are no lights.

**Comment by Kuranes** [comment] 2015-02-19 08:19
Isn't already the case ?
In no light case it ends "diffuse+emission" ?

**Comment by jtorresfabra** [comment] 2015-02-19 08:26
In "no normals" case it should be emission + texture. Isn't it?

You can try the example quad-texture. Comment previously the assignment of normals in createTexturedQuadGeometry() in Shape.js. The emissive material woks, but it is not merged with texture color. In my opinion it should. Thoughts?

**Comment by Kuranes** [comment] 2015-02-19 08:32
Cannot reproduce ?
Commented that [line](https://github.com/cedricpinson/osgjs/blob/bugfix/emissionRename/sources/osg/Shape.js#L400) and still does the emission+texture ?

**Comment by jtorresfabra** [comment] 2015-02-19 08:40
Yep that's the line to comment
That's what I see. I expected to see the texture merged with the material.

![bug-emission](https://cloud.githubusercontent.com/assets/1784900/6263672/0fb004fa-b81b-11e4-9fb9-99771fcce5fb.png)

**Comment by Kuranes** [comment] 2015-02-19 08:44
I get that 
![image](https://cloud.githubusercontent.com/assets/128571/6263719/d977a1bc-b81b-11e4-86c6-1fbf1d88f261.png)

**Comment by Kuranes** [comment] 2015-02-19 08:45
Make sure you pull update the fix/branch, yesterday I amended the Branch several times ?

**Comment by jtorresfabra** [comment] 2015-02-19 08:48
Hehehe, I was about to say to you the same. To make sure that you commited all the changes.
Are that all the changes?
https://github.com/cedricpinson/osgjs/pull/256/files

I am sure I have it.

**Comment by Kuranes** [comment] 2015-02-19 08:59
git fetch origin && git reset --hard origin/bugfix/emissionRename && grunt build
And it worked here.

With "lighter" color, you do get texture merged ?
Perhaps what you mean is that you're expecting "diffuse*emission" rather than "diffuse+emission"

**Comment by jtorresfabra** [comment] 2015-02-19 09:02
No, I guess you have not disabled the normals, after git reset.

**Comment by Kuranes** [comment] 2015-02-19 09:13
if you put  "viewer.setLightingMode( osgViewer.View.LightingMode.NO_LIGHT );" (but re-enable normals in the quadgeom) in the quad texture sample, my guess is that we'll get the same results.

the "no normal" is not handled in osgjs, so shader generated try to use a non existent attribute normal, where there is none. And accessing non initialized data in shader goes into "non determinist" results.
So we get different results because of different  opengl/angle/driver thing, that's why

It's a different issue, then, and that need to be addressed in another issue.
(disable lighting when no normals, or log warning when no normals with lighting or something)

**Comment by jtorresfabra** [comment] 2015-02-19 09:29
Ok, I tested in other computer/Os and I even cannot see the emission color. So agree it's a non determinist result. 

In OSG/OpenGL (fixed pipeline) you can have geometries without normals (think in lines for example), it's quite common. In fact, it used to work in osgjs. 

I'm opening a different issue to talk about that. 

Thanks for the help so far.

**Closed** 2015-02-19 20:50 UTC
Labels: Needs merge
